# Generated by Django 5.2.15 on 2026-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_heartrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='moving_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='sport_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='total_elevation_gain',
            field=models.FloatField(default=0),
        ),
    ]
